import { Injectable } from '@angular/core';
import { IMovie } from '../common/interfaces/IMovie';

@Injectable({
  providedIn: 'root',
})
export class MoviesService {
  constructor() {}
  private allMovies: IMovie[] = [
    {
      adult: false,
      backdrop_path: '/hlZGaey4lR9hc4rGxZRAmIEsZOc.jpg',
      genre_ids: [28, 18],
      id: 1292415,
      title: 'Beast',
      original_language: 'en',
      original_title: 'Beast',
      overview:
        'MMA legend Patton James, now a commercial fisherman, is pulled back into the cage when his brother is in danger. Reuniting with his old coach Sammy, he commits to one final fight in one championship against the brutal champion Xavier Grau.',
      popularity: 80.0016,
      poster_path: '/7NrvUI3vnW8H3rD7ExKcTL7KRcQ.jpg',
      release_date: '2026-04-10',
      softcore: false,
      video: false,
      vote_average: 6.3,
      vote_count: 45,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 1699574,
      title: 'Deool Band 2',
      original_language: 'mr',
      original_title: 'देऊळ बँड 2',
      overview:
        'The story follows a farmer who decides to question and test his faith, setting off a journey filled with emotional and life-altering moments. At its core, the narrative centers on a woman who tirelessly struggles for her family, facing hardships with resilience, as her path ultimately leads her to confront the very idea of divine power',
      popularity: 76.1905,
      poster_path: '/89n9cfc5dm0kdkABmDJalzveEwU.jpg',
      release_date: '2026-05-21',
      softcore: false,
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/bIy0555ukSqweSqG9MtRnoyisQI.jpg',
      genre_ids: [28, 53],
      id: 1122573,
      title: 'In the Grey',
      original_language: 'en',
      original_title: 'In the Grey',
      overview:
        "A covert team of elite operatives are living in the shadows. When a ruthless despot steals a billion-dollar fortune, they're sent to take it back—an impossible heist that erupts into a deadly game of strategy, deception and survival.",
      popularity: 73.2026,
      poster_path: '/dQgIcW6Th08kMRf2HBoYWoFE6OD.jpg',
      release_date: '2026-05-13',
      softcore: false,
      video: false,
      vote_average: 6.574,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: '/bOy625BjpCskOWnx3tD09MsKVCb.jpg',
      genre_ids: [35, 14],
      id: 1368881,
      title: 'Ladies First',
      original_language: 'en',
      original_title: 'Ladies First',
      overview:
        "An arrogant but charismatic ladies' man finds his life of money, power and casual flings upended when he wakes up in a parallel world dominated by women.",
      popularity: 64.3379,
      poster_path: '/kjR56Yv17pbjTVBTMjqepvcus4f.jpg',
      release_date: '2026-05-21',
      softcore: false,
      video: false,
      vote_average: 6.021,
      vote_count: 237,
    },
    {
      adult: false,
      backdrop_path: '/7cHPvy3aF1mDMX1zqmZRt8YE7Vr.jpg',
      genre_ids: [28, 35],
      id: 1316427,
      title: '7 Dogs',
      original_language: 'ar',
      original_title: '7 كلاب',
      overview:
        'Interpol agent Khalid Al-Azzazi joins forces with Ghali Abu Dawood from the 7 Dogs crime syndicate to fight drug trafficking.',
      popularity: 67.5942,
      poster_path: '/66n5bB6iYTWsWMz0mh3Qv7qmzIJ.jpg',
      release_date: '2026-05-27',
      softcore: false,
      video: false,
      vote_average: 4.333,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/zTnAnYIn0Iv3cn0ZHlzLhou3ybm.jpg',
      genre_ids: [9648, 53],
      id: 1368166,
      title: 'The Housemaid',
      original_language: 'en',
      original_title: 'The Housemaid',
      overview:
        'Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.',
      popularity: 66.6006,
      poster_path: '/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
      release_date: '2025-12-18',
      softcore: false,
      video: false,
      vote_average: 7.252,
      vote_count: 2292,
    },
    {
      adult: false,
      backdrop_path: '/eQySd26OW7UmCuaeBOL7qy6foMn.jpg',
      genre_ids: [28, 14, 878],
      id: 454639,
      title: 'Masters of the Universe',
      original_language: 'en',
      original_title: 'Masters of the Universe',
      overview:
        'After being separated for 15 years, the Sword of Power leads Prince Adam back to Eternia, where he discovers his home shattered under the fiendish rule of Skeletor. To save his family and his world, Adam must join forces with his closest allies, Teela and Duncan/Man-At-Arms, and embrace his true destiny as He-Man — the most powerful man in the universe.',
      popularity: 67.9524,
      poster_path: '/3YMd9Ogae4rDKLWuAZFuse9xhc5.jpg',
      release_date: '2026-06-03',
      softcore: false,
      video: false,
      vote_average: 8.1,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: '/8wIaBCeGv3UhIn5CJOWQGHT1Cif.jpg',
      genre_ids: [28, 80, 18, 53],
      id: 1242265,
      title: 'Fuze',
      original_language: 'en',
      original_title: 'Fuze',
      overview:
        'An unexploded WWII bomb is discovered on a busy construction site in the centre of London. Chaos ensues as the military and police begin a mass evacuation against a ticking clock.',
      popularity: 58.9148,
      poster_path: '/oMFdQE5hMJ9JjhNORegwTo0GKmh.jpg',
      release_date: '2026-03-23',
      softcore: false,
      video: false,
      vote_average: 6.471,
      vote_count: 86,
    },
    {
      adult: false,
      backdrop_path: '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
      genre_ids: [18, 9648],
      id: 1330021,
      title: 'Remarkably Bright Creatures',
      original_language: 'en',
      original_title: 'Remarkably Bright Creatures',
      overview:
        'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
      popularity: 59.901,
      poster_path: '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
      release_date: '2026-05-07',
      softcore: false,
      video: false,
      vote_average: 8.552,
      vote_count: 525,
    },
    {
      adult: false,
      backdrop_path: '/t6O6XWelu27BD0OmIDCCufZZT6d.jpg',
      genre_ids: [35, 10751, 9648],
      id: 1301421,
      title: 'The Sheep Detectives',
      original_language: 'en',
      original_title: 'The Sheep Detectives',
      overview:
        "George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must become the detectives. As they follow the clues and investigate human suspects, they prove that even sheep can be brilliant crime-solvers.",
      popularity: 59.9913,
      poster_path: '/hTirV44jiLh6NqdiB6jtxPsDIoG.jpg',
      release_date: '2026-04-30',
      softcore: false,
      video: false,
      vote_average: 7.646,
      vote_count: 144,
    },
    {
      adult: false,
      backdrop_path: '/l1nekhf05HS5OpBr0vRqcD3NxoS.jpg',
      genre_ids: [36, 80, 28, 14],
      id: 1103473,
      title: 'KD – The Devil',
      original_language: 'kn',
      original_title: 'ಕೆಡಿ - ದಿ ಡೆವಿಲ್',
      overview:
        'In the early 1970s, a petty criminal Kaali unwittingly involves himself with underworld thugs, catalyzing events beyond his control.',
      popularity: 70.4246,
      poster_path: '/nEuEMJrnLBneE9tJlmzbhCFLu95.jpg',
      release_date: '2026-04-30',
      softcore: false,
      video: false,
      vote_average: 5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/mHm73HhpvGWfRkXNErcwc15Czrv.jpg',
      genre_ids: [80, 18, 53],
      id: 1628367,
      title: 'Kartavya',
      original_language: 'hi',
      original_title: 'कर्त्तव्य',
      overview:
        "With his family's safety at stake and menacing threats closing in, a police officer must decide how far he'll go to uphold his duty.",
      popularity: 56.4318,
      poster_path: '/doTwMyAphlDL5Z8WqE3elWWvj8M.jpg',
      release_date: '2026-05-15',
      softcore: false,
      video: false,
      vote_average: 6.471,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: '/jDvxsBemt2Iyslg7qn2WMzgxz23.jpg',
      genre_ids: [28, 53, 27],
      id: 1375646,
      title: 'Colony',
      original_language: 'ko',
      original_title: '군체',
      overview:
        'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.',
      popularity: 60.3331,
      poster_path: '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg',
      release_date: '2026-05-21',
      softcore: false,
      video: false,
      vote_average: 6.6,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: '/xA6AM5MvEkieZKlv1Tn3sN23I7i.jpg',
      genre_ids: [28, 18, 10749],
      id: 1630423,
      title: 'My Dearest Assassin',
      original_language: 'th',
      original_title: 'Lueat Rak Nakkha',
      overview:
        'Hunted for her rare blood type, a caged woman vows to fight alongside the assassin she loves to protect their future when an old enemy resurfaces.',
      popularity: 53.2773,
      poster_path: '/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg',
      release_date: '2026-05-06',
      softcore: false,
      video: false,
      vote_average: 8.627,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: '/qYNJm1GOB4nULxIoTO0zfqjSAkC.jpg',
      genre_ids: [53, 27, 35],
      id: 1266127,
      title: 'Ready or Not: Here I Come',
      original_language: 'en',
      original_title: 'Ready or Not: Here I Come',
      overview:
        'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.',
      popularity: 52.6305,
      poster_path: '/13ZcJzSGEqVgDSqsS9U5EkQwPkV.jpg',
      release_date: '2026-03-19',
      softcore: false,
      video: false,
      vote_average: 7.696,
      vote_count: 933,
    },
    {
      adult: false,
      backdrop_path: '/5p6BsJtnPbglYN15MuiUEppPl0f.jpg',
      genre_ids: [9648, 878, 53],
      id: 1275779,
      title: 'Disclosure Day',
      original_language: 'en',
      original_title: 'Disclosure Day',
      overview:
        'If you found out we weren’t alone, if someone showed you, proved it to you, would that frighten you?',
      popularity: 58.475,
      poster_path: '/3o5YPjDGDTcTDL5ftDA9NwN9dLd.jpg',
      release_date: '2026-06-10',
      softcore: false,
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/lj6AaDqDUbzm2XJltFNHeAm2uXN.jpg',
      genre_ids: [35, 27],
      id: 1273221,
      title: 'Scary Movie',
      original_language: 'en',
      original_title: 'Scary Movie',
      overview:
        "Twenty-six years after outrunning a suspiciously familiar masked killer, the Core Four are back in the killer's crosshairs and no horror movie IP is safe.",
      popularity: 56.1572,
      poster_path: '/2OHkZEqQL4OjYXIqWopJu0BijTD.jpg',
      release_date: '2026-06-03',
      softcore: false,
      video: false,
      vote_average: 5.4,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: '/gfRm3ITRJuFm8n6gRJ0L2VLrL5w.jpg',
      genre_ids: [80, 18, 53],
      id: 847742,
      title: 'Drishyam 3',
      original_language: 'ml',
      original_title: 'ദൃശ്യം 3',
      overview:
        'To protect his family and their dark secret, Georgekutty faces an organized new threat. As walls close in and cracks widen, how much more is he willing to sacrifice ?',
      popularity: 49.9584,
      poster_path: '/456FlpiU1iOBnaOxSd783QhZKWw.jpg',
      release_date: '2026-05-21',
      softcore: false,
      video: false,
      vote_average: 7,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: '/b8H1a89qmNxF8rqFGrG93Q9qn52.jpg',
      genre_ids: [10749, 35, 18],
      id: 1325734,
      title: 'The Drama',
      original_language: 'en',
      original_title: 'The Drama',
      overview:
        'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.',
      popularity: 54.4453,
      poster_path: '/89Dw1ujPlIPRLddhzNuJM4F401D.jpg',
      release_date: '2026-03-26',
      softcore: false,
      video: false,
      vote_average: 6.948,
      vote_count: 909,
    },
    {
      adult: false,
      backdrop_path: '/ldUVeDfA5ID2vchHGejrEltoBSN.jpg',
      genre_ids: [12, 18, 10751],
      id: 1662414,
      title: 'Propeller One-Way Night Coach',
      original_language: 'en',
      original_title: 'Propeller One-Way Night Coach',
      overview:
        'During the golden age of aviation, a young airplane enthusiast and his mother embark on a cross-country journey to Hollywood—and their simple flight transforms into the trip of a lifetime.',
      popularity: 46.685,
      poster_path: '/joal4OSVC4T1yFb3kph91tkNNFf.jpg',
      release_date: '2026-05-15',
      softcore: false,
      video: false,
      vote_average: 6.444,
      vote_count: 18,
    },
  ];

  getMovies(): IMovie[] {
    return this.allMovies;
  }

  getMovieById(id: number): IMovie | undefined {
    return this.allMovies.find((movie) => movie.id == id);
  }
}
